platform :ios ,'8.0'
target ‘LMLoveFreshBeen’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.1'
pod 'IQKeyboardManager', '~> 4.0.5'
pod 'MJExtension', '~> 3.0.13'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJRefresh', '~> 3.1.12'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'SDWebImage', '~> 3.8.1'
pod 'MBProgressHUD', '~> 1.0.0'

end

